{% set version = "0.9-27" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-kernlab
  version: {{ version|replace("-", "_") }}

source:
  fn: kernlab_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/kernlab_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/kernlab/kernlab_{{ version }}.tar.gz
  sha256: f6add50ed4097f04d09411491625f8d46eafc4f003b1c1cff78a6fff8cc31dd4

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('kernlab')"  # [not win]
    - "\"%R%\" -e \"library('kernlab')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=kernlab
  license: GPL-2
  summary: Kernel-based machine learning methods for classification, regression, clustering,
    novelty detection, quantile regression and dimensionality reduction.  Among other
    methods 'kernlab' includes Support Vector Machines, Spectral Clustering, Kernel
    PCA, Gaussian Processes and a QP solver.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
