{% set version = "0.9-32" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-kernlab
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/kernlab_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/kernlab/kernlab_{{ version }}.tar.gz
  sha256: 654ef34e343deb4d2c4c139a44e5397d6e38876088ce1c53c7deb087935d6fdc

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('kernlab')"           # [not win]
    - "\"%R%\" -e \"library('kernlab')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=kernlab
  license: GPL-2.0-only
  summary: Kernel-based machine learning methods for classification, regression, clustering, novelty detection, quantile regression and dimensionality reduction.  Among other methods 'kernlab' includes Support Vector Machines, Spectral Clustering, Kernel PCA, Gaussian Processes and a QP solver.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: kernlab
# Version: 0.9-29
# Title: Kernel-Based Machine Learning Lab
# Authors@R: c(person("Alexandros", "Karatzoglou", role = c("aut", "cre"), email = "alexandros.karatzoglou@gmail.com"), person("Alex", "Smola", role = "aut"), person("Kurt", "Hornik", role = "aut"), person("National ICT Australia (NICTA)", role = "cph"), person(c("Michael", "A."), "Maniscalco", role = c("ctb", "cph")), person(c("Choon", "Hui"), "Teo", role = "ctb"))
# Description: Kernel-based machine learning methods for classification, regression, clustering, novelty detection, quantile regression and dimensionality reduction.  Among other methods 'kernlab' includes Support Vector Machines, Spectral Clustering, Kernel PCA, Gaussian Processes and a QP solver.
# Depends: R (>= 2.10)
# Imports: methods, stats, grDevices, graphics
# LazyLoad: Yes
# License: GPL-2
# SystemRequirements: C++11
# NeedsCompilation: yes
# Packaged: 2019-11-12 06:36:20 UTC; hornik
# Author: Alexandros Karatzoglou [aut, cre], Alex Smola [aut], Kurt Hornik [aut], National ICT Australia (NICTA) [cph], Michael A. Maniscalco [ctb, cph], Choon Hui Teo [ctb]
# Maintainer: Alexandros Karatzoglou <alexandros.karatzoglou@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-11-12 07:05:02 UTC
